# Docker Compose file for ELK stack

# Build with:
# docker-compose build elk

# Run with:
# docker-compose up

elk:
  build: .
  ports:
    - "1515:1515"
    - "9200:9200"
    - "5044:5044"
    - "9515:9515"
